name: export-web.yml

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libfontconfig1-dev libcairo2-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libwebp-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590
        with:
          r-version: '4.5.1'

      - uses: r-lib/actions/setup-renv@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590
        with:
          profile: '"default"'

      - name: Install additional packages
        run: renv::install(c("pak", "writexl"))
        shell: Rscript {0}

      - name: Install shinylive
        run: pak::pak("posit-dev/r-shinylive@dfe5d4255275a40dab2d0597ac54c9aee05b415c")
        shell: Rscript {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Export to wasm
        run: |
          Rscript devel/export-shinylive.R

      - name: Zip dist
        run: zip -r anthro-${{ github.ref_name }}-dist.zip dist

      - name: Upload distribution
        uses: actions/upload-artifact@v6
        with:
          name: distribution.zip
          path: anthro-${{ github.ref_name }}-dist.zip

      - name: Upload sbom
        uses: actions/upload-artifact@v6
        with:
          name: sbom.xlsx
          path: sbom_shinylive.xlsx
